---
title: "Webster University 2020 Fall Enrollment Analysis"
author: "Mandy HP Nguyen"
date: "01/04/2022"
output:
  pdf_document:
    toc: yes
    toc_depth: '4'
  html_document:
    theme: paper
    highlight: breezedark
    code_folding: hide
    toc: yes
    toc_depth: 4
    toc_float: yes
    number_sections: yes
  word_document:
    toc: yes
    toc_depth: '4'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Environment Setting

## Load Mandy's Functions

```{r}
source("https://raw.githubusercontent.com/mandyhpnguyen/Mandy-Functions/main/M.R-Funcs/general.R")
```

## Load Packages

```{r}
pkgs <- c(
  "beepr",
  # General pkgs:
  "tidyverse", "dplyr", "summarytools", "reshape2", "pastecs",
  # Analytics pkgs:
  "forecast", "zoo", "scorecard", "ts",
  # Evaluation pkgs:
  "caret", "DT", "lift", "gains", "gt", "cvms", "tibble", "fourfoldplot",
  # Visualization pkgs:
  "RColorBrewer", "hrbrthemes", "knitr", "showtext", "sysfonts",
  "ggfortify", "ggplot2", "corrplot", "GGally", "viridis",
  "lattice", "grid", "cowplot", "Amelia"
)
suppressMessages(suppressWarnings(loadpkg(pkgs)))
```

## Set fonts

```{r}
# Load the main font I used in my paper to plot charts for standardization
windowsFonts(cambria = windowsFont("Cambria"),
             franklin = windowsFont("Franklin Gothic Book"))
my.par <- function() {
  options(scipen = 999)
  par(mfrow = c(1, 1),
      family = "franklin", 
      cex.main = 1.25, cex.lab = 1.25, cex.axis = 1.25)
}
```

## Color Scheme

```{r}
pal <- c("#3A4E84", "#FFAF50", "#4698CA", "#E66622", "#AEAEAE", "#EEEEEE")
pal9 <- c("#3A4E84", "#FFAF50", "#4698CA", "#E66622", "#AEAEAE", "#82d6a9", "#92afd1", "#d3ba3b", "#e896c6")
# Source: https://webster.edu/website-training-resources/editorial-style-color-palette.php
# Color Picker: https://colordesigner.io/random-color-generator
```

# Collect Data

```{r}
# allus20 <- read.csv("https://raw.githubusercontent.com/mandyhpnguyen/Webster-University_Fall-2020_Enrollment_Analysis/main/Data/Final_All_School_US_2020/2020_US_Institutions_data.csv")
wu_race <- read.csv("https://raw.githubusercontent.com/mandyhpnguyen/Webster-University_Fall-2020_Enrollment_Analysis/main/Data/Final_WU_Race_2016-2020/WU_20_Race_data_2.csv")
# wu_gender <- read.csv("https://raw.githubusercontent.com/mandyhpnguyen/Webster-University_Fall-2020_Enrollment_Analysis/main/Data/Final_WU_Gender_2016-2020/WU_20_Gender_data.csv")
```

# WebsterU Race

## Summary

```{r}
round(stat.desc(wu_race), 0)
summary(wu_race)
str(wu_race)
```
## Cleaning

```{r}
race.df <- wu_race
race.df <- race.df[, -1]
race.df$Year <- factor(race.df$Year)
```

```{r}
year_totals <- race.df %>%
    group_by(Race, Year) %>%
    summarise(Student = sum(Student))
race.df <- add_row(.data = race.df, year_totals) %>%
    arrange(Race, Year)
race.df$Gender[is.na(race.df$Gender)] <- "Total"
race.df$Gender <- factor(race.df$Gender, levels = c("Total", "Men", "Women"))
# source: https://stackoverflow.com/questions/66136737/add-total-row-for-each-group-in-a-column-in-df
```

## Descriptive Analysis

### Total Enrollment by Year

```{r}
race.df.gender <- wu_race
```

#### 2020 

```{r}
ggplot(race.df.gender[race.df.gender["Year"] == 2020, ], 
       aes(fill = Gender, y = Student, x = reorder(Race, Student))) + 
  geom_bar(position = "stack", stat = "identity") + coord_flip() +
  labs(title = "Genders & Races in Webster University's 2020 Fall Enrollments",
       subtitle = "Developed by Mandy HP Nguyen",
       caption = "Data source: National Center for Education Statistics\nProject Repository: https://github.com/mandyhpnguyen/Webster-University_Fall-2020_Enrollment_Analysis",
       alt = "Webster University's Fall Enrollments by Mandy HP Nguyen") +
  scale_fill_manual(values = pal[1:2]) + theme_minimal() +
  theme(text = element_text(size = 12, family = "franklin"),
        legend.position = "bottom",
        axis.title.y = element_blank())
```
#### 2019

```{r}
ggplot(race.df.gender[race.df.gender["Year"] == 2019, ], 
       aes(fill = Gender, y = Student, x = reorder(Race, Student))) + 
  geom_bar(position = "stack", stat = "identity") + coord_flip() +
  labs(title = "Genders & Races in Webster University's 2019 Fall Enrollments",
       subtitle = "Developed by Mandy HP Nguyen",
       caption = "Data source: National Center for Education Statistics\nProject Repository: https://github.com/mandyhpnguyen/Webster-University_Fall-2020_Enrollment_Analysis",
       alt = "Webster University's Fall Enrollments by Mandy HP Nguyen") +
  scale_fill_manual(values = pal[1:2]) + theme_minimal() +
  theme(text = element_text(size = 12, family = "franklin"),
        legend.position = "bottom",
        axis.title.y = element_blank())
```

#### 2018

```{r}
ggplot(race.df.gender[race.df.gender["Year"] == 2018, ], 
       aes(fill = Gender, y = Student, x = reorder(Race, Student))) + 
  geom_bar(position = "stack", stat = "identity") + coord_flip() +
  labs(title = "Genders & Races in Webster University's 2018 Fall Enrollments",
       subtitle = "Developed by Mandy HP Nguyen",
       caption = "Data source: National Center for Education Statistics\nProject Repository: https://github.com/mandyhpnguyen/Webster-University_Fall-2020_Enrollment_Analysis",
       alt = "Webster University's Fall Enrollments by Mandy HP Nguyen") +
  scale_fill_manual(values = pal[1:2]) + theme_minimal() +
  theme(text = element_text(size = 12, family = "franklin"),
        legend.position = "bottom",
        axis.title.y = element_blank())
```

#### 2017

```{r}
ggplot(race.df.gender[race.df.gender["Year"] == 2017, ], 
       aes(fill = Gender, y = Student, x = reorder(Race, Student))) + 
  geom_bar(position = "stack", stat = "identity") + coord_flip() +
  labs(title = "Genders & Races in Webster University's 2017 Fall Enrollments",
       subtitle = "Developed by Mandy HP Nguyen",
       caption = "Data source: National Center for Education Statistics\nProject Repository: https://github.com/mandyhpnguyen/Webster-University_Fall-2020_Enrollment_Analysis",
       alt = "Webster University's Fall Enrollments by Mandy HP Nguyen") +
  scale_fill_manual(values = pal[1:2]) + theme_minimal() +
  theme(text = element_text(size = 12, family = "franklin"),
        legend.position = "bottom",
        axis.title.y = element_blank())
```

#### 2016

```{r}
ggplot(race.df.gender[race.df.gender["Year"] == 2016, ], 
       aes(fill = Gender, y = Student, x = reorder(Race, Student))) + 
  geom_bar(position = "stack", stat = "identity") + coord_flip() +
  labs(title = "Genders & Races in Webster University's 2016 Fall Enrollments",
       subtitle = "Developed by Mandy HP Nguyen",
       caption = "Data source: National Center for Education Statistics\nProject Repository: https://github.com/mandyhpnguyen/Webster-University_Fall-2020_Enrollment_Analysis",
       alt = "Webster University's Fall Enrollments by Mandy HP Nguyen") +
  scale_fill_manual(values = pal[1:2]) + theme_minimal() +
  theme(text = element_text(size = 12, family = "franklin"),
        legend.position = "bottom",
        axis.title.y = element_blank())
```

### Total Enrollment by Races 16-20

```{r}
race.df.total <- race.df[race.df["Gender"] == "Total",]
```

```{r}
ggplot(race.df.total[,  c(1, 3, 4)], 
       aes(fill = Year, y = Student, x = reorder(Race, Student))) + 
  geom_bar(position = "dodge", stat = "identity") +
  scale_y_continuous(breaks = seq(0, 7000, by = 1000)) +
  coord_flip() +
  labs(title = "Races & Ethnics Proportion of Webster University's 2016-2020 Fall Enrollments",
       subtitle = "Developed by Mandy HP Nguyen",
       caption = "Data source: National Center for Education Statistics\nProject Repository: https://github.com/mandyhpnguyen/Webster-University_Fall-2020_Enrollment_Analysis",
       alt = "Webster University's Fall Enrollments by Mandy HP Nguyen") +
  scale_fill_manual(values = pal[1:5]) + theme_minimal() +
  theme(text = element_text(size = 12, family = "franklin"),
        legend.position = "bottom",
        axis.title.y = element_blank())
```

```{r}
ggplot(race.df.total[race.df.total["Year"] == 2020,  c(1, 3, 4)], 
       aes(x = "", y = Student, fill = reorder(Race, -Student))) +
  geom_bar(stat = "identity", width = 1, color = "white") +
  coord_polar("y", start = 0) +
  labs(title = "Races & Ethnics Proportion of Webster University's 2020 Fall Enrollments",
       subtitle = "Developed by Mandy HP Nguyen",
       caption = "Data source: National Center for Education Statistics\nProject Repository: https://github.com/mandyhpnguyen/Webster-University_Fall-2020_Enrollment_Analysis",
       alt = "Webster University's Fall Enrollments by Mandy HP Nguyen") +
  scale_fill_manual(values = pal9) + 
  theme_minimal() + theme_void() +
  guides(fill = guide_legend(title = "Races")) +
  theme(text = element_text(size = 12, family = "franklin"),
        legend.position = "left",
        axis.title.y = element_blank())
```

# Gender Change

```{r}
ggplot(race.df, 
       aes(fill = Gender, y = Student, x = Year)) + 
  geom_bar(position = "dodge", stat = "identity") +
  scale_y_continuous(breaks = seq(0, 8000, by = 1000)) +
  labs(title = "Genders Proportion of Webster University's 2016-2020 Fall Enrollments",
       subtitle = "Developed by Mandy HP Nguyen",
       caption = "Data source: National Center for Education Statistics\nProject Repository: https://github.com/mandyhpnguyen/Webster-University_Fall-2020_Enrollment_Analysis",
       alt = "Webster University's Fall Enrollments by Mandy HP Nguyen") +
  scale_fill_manual(values = pal[c(5, 1, 2)]) + theme_minimal() +
  theme(text = element_text(size = 12, family = "franklin"),
        legend.position = "bottom", legend.title = element_blank(),
        axis.title.y = element_blank())
```


# Clean up

```{r}
rm(list = ls())
cat("\014")
```